# Generated by Django 3.2.4 on 2021-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
