# Generated by Django 3.2.4 on 2021-06-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_alter_titles_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['name']},
        ),
    ]
