# Generated by Django 3.2.4 on 2021-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0006_auto_20210616_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
